### ISSUE TITLE
-fopenmp flag fails with clang on macOS

### ISSUE THREAD

**Issue by safonova** [franciscovillaescusa/Pylians3#1]
I'm trying to intall Pylians3 on macOS Mojave (10.14.6) and keep running into the following error:
```
building 'MAS_library.MAS_library' extension
creating build/temp.macosx-10.9-x86_64-3.7
creating build/temp.macosx-10.9-x86_64-3.7/MAS_library
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/opt/anaconda3/include -arch x86_64 -I/opt/anaconda3/include -arch x86_64 -I/usr/local/opt/lapack/include -IMAS_library -I/opt/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/usr/local/Cellar/gcc/9.2.0_3 -I/opt/anaconda3/include/python3.7m -c MAS_library/MAS_library.c -o build/temp.macosx-10.9-x86_64-3.7/MAS_library/MAS_library.o -O3 -ffast-math -march=native -fopenmp
clang: error: unsupported option '-fopenmp'
error: command 'gcc' failed with exit status 1
```
I have tried installing gcc through homebrew, then adding the location of the homebrew gcc to the start of $PATH in my .bash_profile. I've also tried creating an alias to call the homebrew gcc instead of clang when "gcc" is called in my .bash_profile.

Finally, I tried modifying the last command in Pylians3/library/setup.py to be

```
setup(
    name    = 'Pylians3',
    version = "3.0", 
    author  = 'Francisco Villaescusa-Navarro',
    author_email = 'villaescusa.francisco@gmail.com',
    ext_modules = cythonize(ext_modules, 
                            compiler_directives={'language_level' : "3"},
                            include_path=['MAS_library/','void_library/',
                                          'integration_library/']),
    include_dirs=[numpy.get_include(), '/usr/local/Cellar/gcc/'],
    packages=find_packages(),
    py_modules=['bias_library', 'CAMB_library', 'correlation_function_library',
                'cosmology_library', 'HI_image_library/HI_image_library',
                'HOD_library', 'IM_library', 'mass_function_library',
                'plotting_library', 'readfof', 'readgadget', 'readsnapHDF5',
                'readsnap', 'readsnap2', 'readsnap_mpi', 
                'readsubf', 'routines', 'units_library']
)
```
, where I replaced `include_dirs=[numpy.get_include()]` with `include_dirs=[numpy.get_include(), '/usr/local/Cellar/gcc/']`. I am still getting the original clang complaint after all of these. I think clang might not support openMP, but I don't see a way to divert this error from clang to the gcc that will make the Pylians3 setup happy.

**Comment by franciscovillaescusa** [comment]
Hi!

Thanks for raising this up. Unfortunately, I have experienced the same problem as you. Somehow, it is very hard to have openmp with clang in MACs these days :(

My recommendation is to try to install the libraries in a linux environment (e.g. virtual machine) or if you really need to use the Mac try to install the libraries without the openmp flag. If you open the setup.py file, and remove all flags/comments with openmp it should be able to compile the code...

Hope this helps,

Francisco
