### ISSUE TITLE
```gaussian_field_3D``` returns ```Nan```

### ISSUE THREAD

**Issue by WangYun1995** [franciscovillaescusa/Pylians3#10]
Following the example of Pylians3, I use the function ```gaussian_field_3D``` to generate 1024X1024X1024 and 75.0 Mpc/h Gaussian random fields with a given power spectrum. However, the result contains only ```Nan```.

```Python
import numpy as np
import density_field_library as DFL

grid              = 1024    #grid size
BoxSize           = 75.0 #Mpc/h
seed              = 1      #value of the initial random seed
Rayleigh_sampling = 0      #whether sampling the Rayleigh distribution for modes amplitudes
threads           = 1      #number of openmp threads
verbose           = True   #whether to print some information

# read power spectrum; k and Pk have to be floats, not doubles
PowerSpec = np.loadtxt('/home/wangy/FPS_z0.00dm.dat', dtype=np.float32)
k, Pk = PowerSpec[:,0], PowerSpec[:,1]

# generate a 3D Gaussian density field
df_3D = DFL.gaussian_field_3D(grid, k, Pk, Rayleigh_sampling, seed,
                              BoxSize, threads, verbose)
```
The power spectrum file can be download from the link below
[HTTPS：https://pan.baidu.com/s/1uXBFhZ9U21YFDa22VsC9Vg?pwd=nwzi 
PASSWORD：nwzi](url)

**Comment by franciscovillaescusa** [comment]
Apologies for the massive delay with this. I was trying to reproduce the error but I'm having problems downloading the Pk file. Any chance you can put it on github?

**Comment by WangYun1995** [comment]
[FPS_z0.00dm.zip](https://github.com/franciscovillaescusa/Pylians3/files/9457730/FPS_z0.00dm.zip)

**Comment by WangYun1995** [comment]
You can download this file '[FPS_z0.00dm.zip](https://github.com/franciscovillaescusa/Pylians3/files/9457735/FPS_z0.00dm.zip)'
 and then unzip it.

**Comment by franciscovillaescusa** [comment]
Thanks a lot! I managed to reproduce the error. If you use as grid size either 256 or 512 it works well. I think the problem with 1024 is that you will need a power spectrum that goes to higher k. In your case, your Pk file goes to k~43 h/Mpc, that is more or less the wavenumber of the Nyquist frequency. But the code will use higher values of the Pk for the post-nyqvist frequencies. Can you try rerunning the code but using a Pk with higher kmax and let me know? Thanks
