### ISSUE TITLE
Compute Pk error 

### ISSUE THREAD

**Issue by WeakDog** [franciscovillaescusa/Pylians3#2]
Hi, I was wondering if there is function to compute the theoretical error for the measured power spectrum. Thanks!

**Comment by franciscovillaescusa** [comment]
I guess by theoretical error you mean the covariance matrix? If so, there is simple formula that is valid in the linear regime: dP(k) = P(k) / sqrt(N(k)), where N(k) is the number of independent modes within each k-bin. In the non-linear regime things are more complicated, and a traditional approach is just to measure it using many different P(k) from different realizations. Hope this helps...
