### ISSUE TITLE
Helping installation on MacOS (avoiding openmp and mkl issues)

### ISSUE THREAD

**Issue by acwgough** [franciscovillaescusa/Pylians3#4]
These are the steps I took to install Pylians3 on my Mac (High Sierra 10.13.6). My python distribution is miniconda3 (python 3.8.6)

- Download the Pylians3 code from this repository

- In a new conda environment (`conda create --name myenv python=3.x.x`), install the dependency packages laid out in the documentation.md file (numpy, scipy, h5py, pyfftw, mpi4py, cython, openmp) in this new environment.

- Using homebrew, install llvm and libomp by running:
  - `brew install llvm`
  - `brew install libomp`

- navigate to the Pylians3-master/library directory. In there, open setup.py in a text editor. Delete every instance of '-fopenmp'

- in a terminal, while in Pylians3-master/library, run `python setup.py install`

- to test the installation, navigate to Pylians3-master directory, and run `python Tests/import_libraries.py`

This has worked for me, and may help other mac users in installing Pylians

**Comment by acwgough** [comment]
Addendum: creating a separate conda environment is not strictly necessary, but doing so means that anything going wrong is limited to just that environment. 

Additionally, after creating the new environment you need to navigate into that environment using `conda activate myenv`. When you wish to leave the environment use `conda deactivate`.

**Comment by franciscovillaescusa** [comment]
Thank you very much for this! I'll add it to the documentation.
Thank you!

**Comment by franciscovillaescusa** [comment]
I have updated the documentation with your instructions. If you see anything wrong please let me know. And thank you very much once again for this. I never managed to have them installed in recent MacOS versions

**Comment by acwgough** [comment]
Looks good to me, glad it was helpful!
